/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VehicleTable: typeof import('./components/Vehicle/VehicleTable.vue')['default']
    VehicleTableFilter: typeof import('./components/Vehicle/VehicleTableFilter.vue')['default']
    VehicleTableHeadersConfig: typeof import('./components/Vehicle/VehicleTableHeadersConfig.vue')['default']
  }
}
